### ISSUE TITLE
how do you connect ? 

### ISSUE THREAD

**Issue by MattL0** [jonferreira/node-red-contrib-alexa-remote#1]
I do not have cookies and i receive a message saying i have to enter the letter as seens in the box

**Comment by MattL0** [comment]
ok got it working thanks !

but i think just the tts works.

**Comment by jonferreira** [comment]
Glad to hear @MattL0 

This is still pretty much in its infancy with zero documentation but will try to update it this week. 

What problems are you having with the other nodes? I don't see any reason why they wouldn't work

**Comment by MattL0** [comment]
Hi Jon ,

I tried the command node. To change the sound. But the sound remain the same.

I just realised that when i set a sound level with a tts . The tts works. But the sound stay at the same level.

I didn’t try anything else

**Comment by MattL0** [comment]
Ok just tried the pause command . It works. I do not use amazon for music etc . So i tried with a sample of a song. 

Sorry , i think it is just the sound level wich does not work for now

**Comment by MattL0** [comment]
...ho my bad...

I am using the openhab binding echo control... 

And the sound control is in % . 

All your nodes are working ! Sorry

**Comment by MattL0** [comment]
here's a node red flow for volume control. 
So Openhab send it to node-red than node red, send it to my Homeseer program via mqtt ( here i do some manipulation)... than resend it to node-red via mqtt ... than to openhab. 

The values and control works on both platforms instantly  ( openhab and homeseer hs3).

https://ibb.co/eELixU

`[{"id":"b314e63e.841178","type":"tab","label":"Alexa (OPENHAB-HS3)","disabled":false,"info":""},{"id":"65db8224.b4a88c","type":"mqtt in","z":"b314e63e.841178","name":"MQTT Volume","topic":"Automation/Alexa/Salon/Volume","qos":"2","broker":"dd43d627.a59158","x":85,"y":70.18182468414307,"wires":[["b0251572.4a1958"]]},{"id":"fbf28567.802488","type":"debug","z":"b314e63e.841178","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":592,"y":324,"wires":[]},{"id":"3a02eeb6.c1a3d2","type":"mqtt out","z":"b314e63e.841178","name":"Alexa/Volume/salon","topic":"Alexa/Volume/salon","qos":"2","retain":"","broker":"dd43d627.a59158","x":250,"y":20,"wires":[]},{"id":"1c414642.ef0dda","type":"mqtt out","z":"b314e63e.841178","name":"Alexa/Volume/Laundry","topic":"Alexa/Volume/Laundry","qos":"2","retain":"","broker":"dd43d627.a59158","x":240,"y":120,"wires":[]},{"id":"106d046.0a9edfc","type":"mqtt in","z":"b314e63e.841178","name":"MQTT Volume","topic":"Automation/Alexa/Laundry/Volume","qos":"2","broker":"dd43d627.a59158","x":75,"y":171.54543685913086,"wires":[["15baab94.ba5924"]]},{"id":"e1a17ac.d7f6b88","type":"mqtt out","z":"b314e63e.841178","name":"Alexa/Volume/Kitchen","topic":"Alexa/Volume/Kitchen","qos":"2","retain":"","broker":"dd43d627.a59158","x":240,"y":220,"wires":[]},{"id":"9db14e9b.7ae59","type":"mqtt in","z":"b314e63e.841178","name":"MQTT Volume","topic":"Automation/Alexa/Kitchen/Volume","qos":"2","broker":"dd43d627.a59158","x":80,"y":280,"wires":[["3a1eb869.4cc728"]]},{"id":"c1e6941c.248168","type":"mqtt out","z":"b314e63e.841178","name":"Alexa/Volume/hallway","topic":"Alexa/Volume/Hallway","qos":"2","retain":"","broker":"dd43d627.a59158","x":220,"y":340,"wires":[]},{"id":"8de36f31.16f06","type":"mqtt in","z":"b314e63e.841178","name":"MQTT Volume","topic":"Automation/Alexa/Hallway/Volume","qos":"2","broker":"dd43d627.a59158","x":75,"y":388.0909729003906,"wires":[["54fbf0a7.a21c9"]]},{"id":"798f64a3.08e0cc","type":"mqtt out","z":"b314e63e.841178","name":"Alexa/Volume/Salon2","topic":"Alexa/Volume/Salon2","qos":"2","retain":"","broker":"dd43d627.a59158","x":240,"y":440,"wires":[]},{"id":"e9be3070.dbee4","type":"mqtt in","z":"b314e63e.841178","name":"MQTT Volume","topic":"Automation/Alexa/Salon2/Volume","qos":"2","broker":"dd43d627.a59158","x":90,"y":480,"wires":[["1f5ab01c.7399c"]]},{"id":"f08cb46.320bc48","type":"mqtt out","z":"b314e63e.841178","name":"Alexa/Volume/Bedroom","topic":"Alexa/Volume/Bedroom","qos":"2","retain":"","broker":"dd43d627.a59158","x":270,"y":540,"wires":[]},{"id":"27d69806.777928","type":"mqtt in","z":"b314e63e.841178","name":"MQTT Volume","topic":"Automation/Alexa/Bedroom/Volume","qos":"2","broker":"dd43d627.a59158","x":75,"y":590.0910120010376,"wires":[["bd786412.2d6658"]]},{"id":"f591dea5.3c5f5","type":"openhab2-in","z":"b314e63e.841178","name":"Salon","controller":"c232b297.e2e5d","itemname":"LivingRoom_Volume","x":50,"y":20,"wires":[["3a02eeb6.c1a3d2","fbf28567.802488"],[]]},{"id":"b0251572.4a1958","type":"openhab2-out","z":"b314e63e.841178","name":"","controller":"c232b297.e2e5d","itemname":"LivingRoom_Volume","topic":"ItemCommand","payload":"","x":280,"y":60,"wires":[]},{"id":"a7267123.96f37","type":"openhab2-in","z":"b314e63e.841178","name":"Laundry","controller":"c232b297.e2e5d","itemname":"Laundry_Volume","x":60,"y":120,"wires":[["1c414642.ef0dda","fbf28567.802488"],[]]},{"id":"8da07652.dede28","type":"openhab2-in","z":"b314e63e.841178","name":"Kitchen","controller":"c232b297.e2e5d","itemname":"Kitchen_Volume","x":55,"y":218.01620483398438,"wires":[["e1a17ac.d7f6b88","fbf28567.802488"],[]]},{"id":"a4c8f275.86fce","type":"openhab2-in","z":"b314e63e.841178","name":"Hallway","controller":"c232b297.e2e5d","itemname":"Hallway_Volume","x":55,"y":332.0162048339844,"wires":[["c1e6941c.248168","fbf28567.802488"],[]]},{"id":"970d23a2.53016","type":"openhab2-in","z":"b314e63e.841178","name":"Salon 2","controller":"c232b297.e2e5d","itemname":"LvRoom2_Volume","x":70,"y":440,"wires":[["798f64a3.08e0cc","fbf28567.802488"],[]]},{"id":"6871fd91.8d00d4","type":"openhab2-in","z":"b314e63e.841178","name":"Bedroom","controller":"c232b297.e2e5d","itemname":"Bedroom_Volume","x":65,"y":535.3495483398438,"wires":[["fbf28567.802488","f08cb46.320bc48"],[]]},{"id":"15baab94.ba5924","type":"openhab2-out","z":"b314e63e.841178","name":"","controller":"c232b297.e2e5d","itemname":"Laundry_Volume","topic":"ItemCommand","payload":"","x":270,"y":160,"wires":[]},{"id":"3a1eb869.4cc728","type":"openhab2-out","z":"b314e63e.841178","name":"","controller":"c232b297.e2e5d","itemname":"Kitchen_Volume","topic":"ItemCommand","payload":"","x":260,"y":280,"wires":[]},{"id":"54fbf0a7.a21c9","type":"openhab2-out","z":"b314e63e.841178","name":"","controller":"c232b297.e2e5d","itemname":"Hallway_Volume","topic":"ItemCommand","payload":"","x":270,"y":400,"wires":[]},{"id":"1f5ab01c.7399c","type":"openhab2-out","z":"b314e63e.841178","name":"","controller":"c232b297.e2e5d","itemname":"LvRoom2_Volume","topic":"ItemCommand","payload":"","x":290,"y":480,"wires":[]},{"id":"bd786412.2d6658","type":"openhab2-out","z":"b314e63e.841178","name":"","controller":"c232b297.e2e5d","itemname":"Bedroom_Volume","topic":"ItemCommand","payload":"","x":270,"y":600,"wires":[]},{"id":"dd43d627.a59158","type":"mqtt-broker","z":"","name":"","broker":"127.0.0.1","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"c232b297.e2e5d","type":"openhab2-controller","z":"","name":"Openhab","protocol":"http","host":"127.0.0.1","port":"8080","path":"","username":"","password":""}]`

**Comment by MattL0** [comment]
So, thanks for you work ! In the future, IF this project is maintained, i will stop using openhab ( i only use openhab because of this binding...) , and use your nodes instead. This will permit me to reduce the load my server. 

here is the last version of openhab echocontrol binding ( I am using the 3rd beta 2.4 version) . https://community.openhab.org/t/released-openhab2-amazon-echo-control-binding-controlling-alexa-from-openhab2/37844

**Comment by MattL0** [comment]
here is a picture of another flow for ''alexa last command'' ( with this you can have room awareness for anything you want )

https://ibb.co/e3QYxU

`[{"id":"269bc6ba.5d755a","type":"tab","label":"Alexa (OPENHAB-HS3) LVC","disabled":false,"info":""},{"id":"e89c3b8d.b4cb58","type":"debug","z":"269bc6ba.5d755a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":670,"y":180,"wires":[]},{"id":"a62b67b1.6ee1b8","type":"mqtt out","z":"269bc6ba.5d755a","name":"Alexa/LastVoiceCommand/salon","topic":"Alexa/LastVoiceCommand/salon","qos":"2","retain":"","broker":"dd43d627.a59158","x":305,"y":49.818175315856934,"wires":[]},{"id":"3630e2f1.e163ce","type":"mqtt out","z":"269bc6ba.5d755a","name":"Alexa/LastVoiceCommand/Laundry","topic":"Alexa/LastVoiceCommand/Laundry","qos":"2","retain":"","broker":"dd43d627.a59158","x":303,"y":99,"wires":[]},{"id":"df26265b.1cd268","type":"mqtt out","z":"269bc6ba.5d755a","name":"Alexa/LastVoiceCommand/Kitchen","topic":"Alexa/LastVoiceCommand/Kitchen","qos":"2","retain":"","broker":"dd43d627.a59158","x":308,"y":145,"wires":[]},{"id":"865bfba.4463a08","type":"mqtt out","z":"269bc6ba.5d755a","name":"Alexa/LastVoiceCommand/Hallway","topic":"Alexa/LastVoiceCommand/Hallway","qos":"2","retain":"","broker":"dd43d627.a59158","x":346,"y":188,"wires":[]},{"id":"1117d00c.a4fbd","type":"mqtt out","z":"269bc6ba.5d755a","name":"Alexa/LastVoiceCommand/Salon2","topic":"Alexa/LastVoiceCommand/Salon2","qos":"2","retain":"","broker":"dd43d627.a59158","x":353,"y":228,"wires":[]},{"id":"a6037c43.31347","type":"mqtt out","z":"269bc6ba.5d755a","name":"Alexa/LastVoiceCommand/Bedroom","topic":"Alexa/LastVoiceCommand/Bedroom","qos":"2","retain":"","broker":"dd43d627.a59158","x":420,"y":280,"wires":[]},{"id":"97a6d936.fabd68","type":"openhab2-in","z":"269bc6ba.5d755a","name":"Salon","controller":"c232b297.e2e5d","itemname":"LivingRoom_LastVoiceCommand","x":74,"y":46,"wires":[["a62b67b1.6ee1b8","e89c3b8d.b4cb58"],[]]},{"id":"ab204487.aa1e08","type":"openhab2-in","z":"269bc6ba.5d755a","name":"Laundry","controller":"c232b297.e2e5d","itemname":"Laundry_LastVoiceCommand","x":65,"y":101,"wires":[["3630e2f1.e163ce","e89c3b8d.b4cb58"],[]]},{"id":"ff6b75b7.484a38","type":"openhab2-in","z":"269bc6ba.5d755a","name":"Kitchen","controller":"c232b297.e2e5d","itemname":"Kitchen_LastVoiceCommand","x":55,"y":145,"wires":[["e89c3b8d.b4cb58","df26265b.1cd268"],[]]},{"id":"e4fe106.9f48ef","type":"openhab2-in","z":"269bc6ba.5d755a","name":"Hallway","controller":"c232b297.e2e5d","itemname":"Hallway_LastVoiceCommand","x":81,"y":188,"wires":[["865bfba.4463a08","e89c3b8d.b4cb58"],[]]},{"id":"abf80595.214bb8","type":"openhab2-in","z":"269bc6ba.5d755a","name":"Salon 2","controller":"c232b297.e2e5d","itemname":"LvRoom2_LastVoiceCommand","x":85,"y":231,"wires":[["e89c3b8d.b4cb58","1117d00c.a4fbd"],[]]},{"id":"b7d93e84.fc098","type":"openhab2-in","z":"269bc6ba.5d755a","name":"Bedroom","controller":"c232b297.e2e5d","itemname":"Bedroom_LastVoiceCommand","x":63,"y":279,"wires":[["e89c3b8d.b4cb58","a6037c43.31347"],[]]},{"id":"dd43d627.a59158","type":"mqtt-broker","z":"","name":"","broker":"127.0.0.1","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"c232b297.e2e5d","type":"openhab2-controller","z":"","name":"Openhab","protocol":"http","host":"127.0.0.1","port":"8080","path":"","username":"","password":""}]`

**Comment by jonferreira** [comment]
Looks good, I'll take a look when I get some spare time

**Comment by peadard** [comment]
> receive a message saying

@MattL0 I am getting the same error msg " you must enter the characters as they appear....."
How did you get around this?
Cheers.

**Comment by MattL0** [comment]
Thank @jonferreira 

@peadard  Take a look at my post here : https://github.com/jonferreira/node-red-contrib-alexa-remote/issues/2

**Comment by peadard** [comment]
Thanks @MattL0 I think still having the browser window was somehow causing the Captcha.
