### ISSUE TITLE
How to pass speech in Msg.payload?

### ISSUE THREAD

**Issue by peadard** [jonferreira/node-red-contrib-alexa-remote#3]
Hi Just wondering how we should pass speech to the Alexa.Speak node?
If I fill in the field "Text" in the node then it works perfectly but I would prefer to pass the information in Msg.payload or Msg.text.
Can this be done??
Thanks.

**Comment by jonferreira** [comment]
yes msg.text for now although on next release I'll change that to msg.payload.text

**Comment by jonferreira** [comment]
updated to msg.payload.text

**Comment by anttif** [comment]
Running latest version but msg.payload.text nor msg.text seems to work. It doesn't override...
