### ISSUE TITLE
Overriding variable with msg.text or msg.payload.text

### ISSUE THREAD

**Issue by anttif** [jonferreira/node-red-contrib-alexa-remote#6]
Running latest version but msg.payload.text nor msg.text doesn't override settings...

**Comment by 586837r** [comment]
It works for me when I set msg.payload.text. Are you sure msg.payload.text is sent to the Alexa Speak Node?

**Comment by anttif** [comment]
I got this finally working.

I had made some changes to get msg.text working in past. That was the issue.

Sorry to bother you.

**Comment by jonferreira** [comment]
Glad you got it sorted
